---
- hosts: common
  gather_facts: yes # needed for trusty workaround
  vars:
    append_bin_path: 'PATH=$PATH:{{ bin_dir }}'
  tasks:
    - debug: var=installer
    - debug: var=install_dir
    - file: path={{ install_dir }} state=directory
    - yum: name=libselinux-python
      when: ansible_distribution == 'CentOS'
    - copy: src=installers/{{ installer }} dest={{ install_dir }}/ mode=0755
    - block:
        - unarchive: src={{ install_dir }}/{{ installer | basename }}
                     dest={{ install_dir }}/ copy=no
                     creates={{ install_dir }}/version.txt
        - command: ./install.bin -i silent -f production.properties
                   chdir={{ install_dir }}/cloudant-installer
                   creates=/root/cloudant
          when: is_cast_installer
      when: not is_binary_installer
    - command: ./{{ installer }} -- -s
               chdir={{ install_dir }}
               creates=/opt/cloudant/cast
      when: is_binary_installer
    - file: path={{ config_dir }} state=directory
    - lineinfile: line="alias r='sudo su - root'" dest=/home/vagrant/.bashrc
    - file: path=/root/.bashrc state=touch
    - lineinfile: dest=/root/.bashrc line={{ append_bin_path }}
    - lineinfile: dest=/home/vagrant/.bashrc line={{ append_bin_path }}

    # workaround for dependency bug on trusty
    - block:
        - apt: name=libffi-dev
        - apt: name=libssl-dev autoremove=yes
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
