---
# extra db nodes which will be added to cluster
- hosts: dbx
  gather_facts: no
  tasks:
    - command: cast system install -db -c {{ cluster_config_path }}
               creates=/opt/cloudant/lib
