---
- hosts: db
  tasks:
    - block:
        - debug: var=new_node
        - debug: var=domain
        - command: cast cluster add {{ new_node }}.{{ domain }}
      when: is_first_node

- hosts: lb
  tasks:
    - command: cp /opt/cloudantrebal/rebal.ini /root/
    - file: path=/root/rebaldir state=directory
    - command: rebal plan expand {{ new_node }}.{{ domain }}
    - command: rebal run rebalance_plan
    # TODO: reconfigure haproxy
