---
- hosts: lb
  gather_facts: yes
  tasks:
    - command: cast system install -lb creates=/etc/haproxy # better path?
    - template: src=src/lbnode.yaml dest={{ cast_config_dir }}/
    - command: cast node config {{ cast_config_dir }}/lbnode.yaml

    - replace: |
        dest=/opt/cloudant/etc/mustgather.ini regexp="^nodes:"
        replace="nodes: {{ ', '.join((db_nodes + lb_nodes) | map(attribute='fqdn') | list) }}"

    - name: ensure rebal works
      command: rebal -h

    # workaround for haproxy bug on precise
    - block:
        - replace: dest=/etc/haproxy/haproxy.cfg
                   regexp='^  bind [*]:80'
                   replace='#  bind *:80'
        - command: cast node restart
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'
