---
- hosts: lb
  gather_facts: yes
  environment:
    PATH: '{{ ansible_env.PATH }}:{{ cast_venv_bin_dir }}:{{ mustgather_venv_bin_dir }}:{{ rebal_venv_bin_dir }}'
  tasks:
    - debug: var=config_dir
    - command: cast system install -lb creates=/etc/haproxy # better path?
    - template: src=src/lbnode.yaml dest={{ config_dir }}/
    - command: cast node config {{ config_dir }}/lbnode.yaml

    - replace: |
        dest=/opt/cloudant/etc/mustgather.ini regexp='^nodes:$'
        replace="nodes: {{ ', '.join((db_nodes + lb_nodes) | map(attribute='fqdn') | list) }}"
      when: version >= '1.1.0'

    - include: work-around-precise-haproxy.yaml

    - include: verify-lb.yaml

    - include: verify-firewall.yaml
      vars:
        ports:
          - 80
          - 443
