---
- hosts: lb
  gather_facts: no
  tasks:
    - command: cast system install -lb creates=/etc/haproxy # better path?
    - template: src=src/lbnode.yaml dest={{ cast_config_dir }}/
    - command: cast node config {{ cast_config_dir }}/lbnode.yaml

    - copy: src={{ item }} dest=/root/.ssh/ mode=0600
      with_fileglob:
        - ssh/id_rsa*
    - file: path=/root/.ssh/config state=touch mode=0644
    - name: configure ssh client
      blockinfile:
        dest: /root/.ssh/config
        block: |
          Host *{{ domain }}
            StrictHostKeyChecking no
            User cloudantrebal
    - template: src=src/rebal.ini dest={{ rebal_dir }}/

