---
- hosts: lb
  gather_facts: no
  tasks:
    - command: cast system install -lb creates=/etc/haproxy # better path?
    - template: src=src/lbnode.yaml dest={{ cast_config_dir }}/
    - command: cast node config {{ cast_config_dir }}/lbnode.yaml
