---
- hosts: lb
  gather_facts: yes
  tasks:
    - yum: name=epel-release state=latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - command: cast system install -lb creates=/etc/haproxy # better path?
    - template: src=src/lbnode.yaml dest={{ cast_config_dir }}/
    - command: cast node config {{ cast_config_dir }}/lbnode.yaml

    # workaround for haproxy bug on precise
    - block:
        - replace: dest=/etc/haproxy/haproxy.cfg
                   regexp='^  bind [*]:80'
                   replace='#  bind *:80'
        - command: cast node restart
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'
